name: Python package

on:
  push:
    branches:
    - main
  pull_request:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Run unit tests
        run: uv run pytest -v
      - name: Verify that we can build the package
        run: uv build
  lint:
    name: Linting build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Check style against standards using ruff
        run: |
          uvx ruff check
          uvx ruff format --check
